In [1]:
import pandas as pd
ratings1 = pd.read_csv('/home/dana/ide/project_0/data/ratings1.csv')
ratings2 = pd.read_csv('/home/dana/ide/project_0/data/ratings2.csv')
dates = pd.read_csv('/home/dana/ide/project_0/data/dates.csv')
movies = pd.read_csv('/home/dana/ide/project_0/data/movies.csv')

In [2]:
movies.nunique()
ratings1.nunique()
dates = pd.to_datetime(dates['date'])
dates.dt.year.value_counts()

date
2000    10061
2017     8198
2007     7114
2016     6703
2015     6616
2018     6418
1996     6040
2005     5813
2012     4656
2008     4351
2009     4158
2006     4059
2003     4014
2001     3922
2002     3478
2004     3279
1999     2439
2010     2301
1997     1916
2011     1690
2013     1664
2014     1439
1998      507
Name: count, dtype: int64

In [3]:
#concat()
#objs — список объектов DataFrame ([df1, df2,…]), которые должны быть сконкатенированы;
#axis — ось определяет направление конкатенации: 0 — конкатенация по строкам (по умолчанию), 1 — конкатенация по столбцам;
#join — либо inner (пересечение), либо outer (объединение); рассмотрим этот момент немного позже;
#ignore_index — по умолчанию установлено значение False, которое позволяет значениям индекса оставаться такими, какими они были в исходных данных.
#Если установлено значение True, параметр будет игнорировать исходные значения и повторно назначать значения индекса в последовательном порядке.

ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True
   )
display(ratings)

print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

display(ratings1.tail(1))
display(ratings2.head(1))

ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

Число строк в таблице ratings:  100836

        userId  movieId  rating                date
100829     610   164179     5.0 2017-05-03 21:07:11
100830     610   166528     4.0 2017-05-04 06:29:25
100831     610   166534     4.0 2017-05-03 21:53:22
100832     610   168248     5.0 2017-05-03 22:21:31
100833     610   168250     5.0 2017-05-08 19:50:47
100834     610   168252     5.0 2017-05-03 21:19:12
100835     610   170875     3.0 2017-05-03 21:20:15

In [4]:
#join()
#other — таблица, которую мы присоединяем. При объединении она является «правой», а исходная таблица, от имени которой вызывается метод, является «левой».
#how — параметр типа объединения. Он может принимать значения 'inner', 'left' (left outer), 'right' (right outer), и 'outer' (full outer). По умолчанию параметр установлен на 'left'.
#on — параметр, который определяет, по какому столбцу в «левой» таблице происходит объединение по индексам из «правой».
#lsuffix и rsuffix — дополнения (суффиксы) к названиям одноимённых столбцов в «левой» и «правой» таблицах.

joined_false = ratings_dates.join(
    movies,
    rsuffix='_right',
    how='left'
)
display(joined_false)

joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,NaN,NaN,NaN

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [5]:
#merge()
#right — присоединяемая таблица. По умолчанию она является «правой».
#how — параметр типа объединения. По умолчанию принимает значение 'inner'.
#on — параметр, который определяет, по какому столбцу происходит объединение. Определяется автоматически, но рекомендуется указывать вручную.
#left_on — если названия столбцов в «левой» и «правой» таблицах не совпадают, то данный параметр отвечает за наименования ключевого столбца исходной таблицы.
#right_on — аналогично предыдущему, параметр отвечает за наименование ключевого столбца присоединяемой таблицы.

merged = ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
display(merged.head())

print('Число строк в таблице ratings_dates: ', ratings_dates.shape[0])
print('Число строк в таблице merged: ', merged.shape[0])
print(ratings_dates.shape[0] == merged.shape[0])

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

Число строк в таблице ratings_dates:  100836
Число строк в таблице merged:  100836
True

In [6]:
merged2 = ratings_dates.merge(
    movies,
    on='movieId',
    how='outer'
)
print('Число строк в таблице merged2: ', merged2.shape[0])
display(merged2.tail())

Число строк в таблице merged2:  100854

,userId,movieId,rating,date,title,genres
100849,184.0,193581,4.0,2018-09-16 14:44:42,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
100850,184.0,193583,3.5,2018-09-16 14:52:25,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
100851,184.0,193585,3.5,2018-09-16 14:56:45,Flint (2017),Drama
100852,184.0,193587,3.5,2018-09-16 15:00:21,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
100853,331.0,193609,4.0,2018-09-17 04:13:26,Andrew Dice Clay: Dice Rules (1991),Comedy

In [7]:
merge_ratings = ratings1.merge(ratings2, how='outer')
print('Число строк в таблице merge_ratings: ', merge_ratings.shape[0])
display(merge_ratings)

Число строк в таблице merge_ratings:  100836

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [8]:
ratings_movies = pd.read_csv('/home/dana/ide/project_0/data/ratings_movies.csv')

In [9]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

In [10]:
ratings_movies['year_release']=ratings_movies['title'].apply(get_year_release)
ratings_movies['year_release'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100836 entries, 0 to 100835
Series name: year_release
Non-Null Count   Dtype
--------------   -----
100818 non-null  float64
dtypes: float64(1)
memory usage: 787.9 KB

In [11]:
mask_title=ratings_movies['year_release']==1999
ratings_movies[mask_title].groupby('title')['rating'].mean().sort_values()

title
Bloodsport: The Dark Kumite (1999)                  0.5
Trippin' (1999)                                     1.0
Chill Factor (1999)                                 1.0
From Dusk Till Dawn 2: Texas Blood Money (1999)     1.0
Simon Sez (1999)                                    1.0
                                                   ...
Mickey's Once Upon a Christmas (1999)               5.0
On the Ropes (1999)                                 5.0
Trailer Park Boys (1999)                            5.0
Five Senses, The (1999)                             5.0
George Carlin: You Are All Diseased (1999)          5.0
Name: rating, Length: 261, dtype: float64

In [13]:
ratings_movies.groupby('userId')['genres'].nunique().sort_values()

userId
245     13
85      13
214     13
494     15
578     15
      ...
474    395
380    399
448    403
414    482
599    524
Name: genres, Length: 610, dtype: int64

In [21]:
ratings_movies.groupby('userId')['rating'].agg(['count', 'mean']).sort_values(by=['count','mean'],ascending=[True, False])

        count      mean
userId
53         20  5.000000
595        20  4.200000
189        20  4.100000
569        20  4.000000
278        20  3.875000
...       ...       ...
274      1346  3.235884
448      1864  2.847371
474      2108  3.398956
599      2478  2.642050
414      2698  3.391957

[610 rows x 2 columns]

In [ ]:
mask_genre=ratings_movies['year_release']==2018
genre_grouped = ratings_movies[mask_genre].groupby('genres')['rating'].agg(
    ['mean', 'count']
)
genre_grouped[genre_grouped['count']>10].sort_values(
    by='mean', ascending=False
)

                             mean  count
genres
Action|Adventure|Sci-Fi  3.928571     14
Action|Comedy|Sci-Fi     3.875000     12

In [42]:
ratings_movies.head()
ratings_movies['date']=pd.to_datetime(ratings_movies['date'])
ratings_movies['year_rating']=ratings_movies['date'].dt.year
ratings_movies.groupby(['genres', 'year_rating'])['rating'].mean()

genres              year_rating
(no genres listed)  2015           0.500000
                    2016           3.500000
                    2017           3.000000
                    2018           3.676471
Action              1996           2.730769
                                     ...
Western             2014           4.000000
                    2015           3.900000
                    2016           3.958333
                    2017           2.933333
                    2018           3.611111
Name: rating, Length: 9273, dtype: float64